server:
  port: 8181
spring:
  datasource:
    username: root
    password: QdNfBUl+g3NfG8fuH4TvlvDP7ulMb1SqAKu1OtHBdKi1xlE48AsplYlLrCCUpLz7bfXzrJALa4xnMVEZ6uetPw==
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.157.71:3306/video_danmaku
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOKLJNbdvZb6wbP0Wo7pxv+Pi5TokeyU24/M5qUDBsBKW+1yPPa2yo97bFHiJ0RNXI2FhALFB0TBvFPx8RM3n38CAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml

