server:
  port: 5000
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 对所有路径生效
            allowedOrigins: "http://localhost:5173" # 允许前端域名
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*" # 允许所有请求头，包括 satoken
            exposedHeaders: # 暴露给前端的响应头（如需要）
              - "satoken"
            allowCredentials: true # 允许携带凭证（如 Cookie）
#          '[/**]':
#            allowed-origins: "http://localhost:5173" # 允许的前端地址
#            allowed-methods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowed-headers: "*"
#            allow-credentials: true
#            max-age: 3600
      routes:
        - id: oss
          uri: lb://video-danmaku-oss-dev
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://video-danmaku-auth-dev
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: video
          uri: lb://video-danmaku-video-dev
          predicates:
            - Path=/videodisplay/**
          filters:
            - StripPrefix=1

  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 192.168.10.135
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: xdf_danmakuvideo
    # 连接超时时间
    timeout: 2s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
